### ISSUE TITLE
Something is wrong with Initialize-AWSDefaultConfiguration

### ISSUE THREAD

**Issue by LordMike** [awsdocs/aws-powershell-user-guide#9]
Hi,

I've tried a few times now on different computers over a longer period, to setup AWS in powershell using the Initialize cmdlet. But it never really sticks - as in, it works for the current session (Get-EC2Instance returns data) but doesn't persist onto new powershell instances. I finally make it work each time by looking up the documentation and finding that I can put in an AWSCredential named "default", which then sticks.

When troubleshooting this, I go to the location AWS Powershell stores persisted credentials, which according to [this page](https://github.com/awsdocs/aws-powershell-user-guide/blob/master/doc_source/specifying-your-aws-credentials.rst) should be at `C:\Users\<user>\.aws\` - but that directory doesn't exist after an `Initialize-AWSDefaultConfiguration`. Even if I create it, it doesn't get any content on reruns of the cmdlet.

Using procmon from Sysinternals, I've discovered a backing store file for `Get-AWSCredential` (and `Set-`) at this location: `%LocalAppdata%\AWSToolkit`. Shouldn't the docs specify this directory instead?

This directory contains a JSON file with all the details needed - making me believe the `.aws` directory is outdated?

This works for me (order does not seem to matter):
```
Set-AWSCredential -StoreAs default -AccessKey <..some access key..>
Initialize-AWSDefaultConfiguration -Region <..my region..>
```

After this, the JSON file in `%LocalAppdata%\AWSToolkit` contains both my region and credentials. Subsequent sessions will run `Get-EC2Instance` without error.

This does not work for me:
```
Initialize-AWSDefaultConfiguration -Region <..my region..>
```

It creates the JSON file in `%LocalAppdata%\AWSToolkit`, but it only contains my region - it does not contain the credentials I supplied to `Initialize-AWSDefaultConfiguration`.

**Comment by GitGaby** [comment]
Hi, Michael, I believe what you’re seeing is by design.

The cmdlet reference documentation for [Initialize-AWSDefaultConfiguration](http://docs.aws.amazon.com/powershell/latest/reference/items/Initialize-AWSDefaultConfiguration.html), and the [Using AWS Credentials](http://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html#specifying-your-aws-credentials-use) page to which you linked, do state that this cmdlet’s changes don’t persist outside your current PowerShell session.  In the user guide, it states you run Initialize-AWSDefaultConfiguration “…to specify a default profile for every PowerShell session.” The reference topic says, “Creates or updates the credential profile named 'default' and sets the profile, and optionally a region, as active in the current shell.”

The Using AWS Credentials page states that running Initialize-AWSDefaultConfiguration “overwrites any existing profile with that name.” So the fact that the credential store in  `C:\Users\<user>\.aws\ `is missing after you run the cmdlet makes sense, and appears to be by design.  On my system, the `C:\Users\<user>\.aws\ ` directory is still present, because I have not run Initialize-AWSDefaultConfiguration.

It makes sense that Set-AWSCredential worked in combination with Initialize-AWSDefaultConfiguration, because with Set-AWSCredential, you are building a new default profile for the current session.  And when you run Initialize-AWSDefaultConfiguration with only the -Region parameter once again (but no credentials), you are, per the docs, “overwriting any existing profile,” meaning the default profile you created with Set-AWSCredential gets overwritten.

I can try to make this somewhat clearer in the Using AWS Credentials topic.  I can see that this behavior can be confusing.  Per Using AWS Credentials, though, “The preferred approach” for specifying credentials “is to use a profile”.

Thank you for telling us about your experience, and for your help to improve the AWS documentation. -- Gaby

**Comment by LordMike** [comment]
Right. It should probably be explained a bit more (or it could even be that "less is more").

A suggestion for the specific sentence is.

```
Start every PowerShell session by using Initialize-AWSDefaultConfiguration to specify a default profile.
```

Here I've simply reverted the sentence so that it explicitly says that `Initialize-AWSDefaultConfiguration` is to be run multiple times, and not just "once to specify credentials for every (future) session".

-----

Another issue entirely is the location of the config. It seems the JSON file is "the new default" (?), but it isn't mentioned anywhere.

**Comment by GitGaby** [comment]
I've revised the [AWS Credentials topic](https://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html) to provide a bit more prescriptive guidance. Today, there isn't much need for the Initialize-AWSDefaultConfiguration cmdlet unless you are running the AWS Tools for PowerShell on an EC2 instance that has been launched without an instance profile.  Running Initialize-AWSDefaultConfiguration on your local computer can overwrite the default profile with a custom profile that you were using, so it's not without risk.  I believe that's what was happening in the original issue.

Currently, on an EC2 instance launched with an instance profile, AWS Tools for PowerShell will get the credentials and region from the instance profile, so there's really no need to run Initialize-AWSDefaultConfiguration in that case (it will just overwrite the existing default profile with the same information). Although the Initialize-AWSDefaultConfiguration cmdlet has a -Region parameter that allows you to use a region other than the default region for your current session, you can also simply change the region by running Set-DefaultAWSRegion to change the region.  Running Set-DefaultAWSRegion won't change the region in the instance's profile.

We do say in the Credentials Search Order section that the AWS SDK store credentials are used first (see #2 and #5) before the plain-text credentials in %userdata%.
